version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
    environment:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: xxx
      AWS_SECRET_ACCESS_KEY: xxx
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y --no-install-recommends openjdk-7-jre-headless
      - run:
          name: Install bundles
          command: bundle install
      - run:
          name: Execute specs
          command: bundle exec rspec

workflows:
  version: 2
  rspec:
    jobs:
      - build
